server:
  port: "8080"
  mode: "debug"

database:
  path: "./data/websoft9.db"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0

influxdb:
  url: "http://localhost:8086"
  token: "your-influxdb-token"
  org: "websoft9"
  bucket: "metrics"

jwt:
  secret: "websoft9-jwt-secret-key"
  expire_time: 3600

grpc:
  port: "9090"