# Websoft9 Agent 配置文件

# 服务端配置
server:
  host: "localhost"
  port: 9090
  tls: false

# Redis 配置
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

# 日志配置
log:
  level: "info"  # debug, info, warn, error
  file: "/var/log/websoft9/agent.log"

# Agent 配置
agent:
  id: "agent-001"
  heartbeat_interval: 30  # 心跳间隔(秒)
  monitor_interval: 60    # 监控采集间隔(秒)
  work_dir: "/var/lib/websoft9/agent"