# Websoft9 项目 golangci-lint 配置
# 基于开发规范文档的要求配置
# 兼容 golangci-lint v1.x 格式

run:
  timeout: 5m
  tests: false
  go: "1.21"

output:
  formats:
    - format: colored-line-number

linters-settings:
  govet:
    enable:
      - shadow

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 2
    min-occurrences: 2

  misspell:
    locale: US

  lll:
    line-length: 120

  goimports:
    local-prefixes: github.com/websoft9

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

  funlen:
    lines: 100
    statements: 50

  gocognit:
    min-complexity: 15

  nestif:
    min-complexity: 4

  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign

  gomodguard:
    allowed:
      modules: []
      domains: []
    blocked:
      modules: []
      versions: []

  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK

  dogsled:
    max-blank-identifiers: 2

  whitespace:
    multi-if: false
    multi-func: false

linters:
  disable-all: true
  enable:
    # 错误检查
    - errcheck
    - staticcheck # 包含了 gosimple, stylecheck
    - govet
    - ineffassign
    - typecheck
    - unused

    # 安全检查
    - gosec

    # 性能检查
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

    # 代码质量
    - dupl
    - goconst
    - gocritic
    - mnd # 替代 gomnd
    - goprintffuncname
    - nakedret
    - prealloc
    - unconvert
    - unparam

    # 复杂度检查
    - gocyclo
    - gocognit
    - funlen
    - nestif

    # 其他
    - dogsled
    - godox
    - gomodguard
    - misspell
    - whitespace
    - lll

    # 格式化
    - gofmt
    - goimports

issues:
  exclude-dirs:
    - vendor
    - .git
    - bin
    - build
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"
  exclude-rules:
    # 排除测试文件的某些检查
    - path: '_test\.go'
      linters:
        - mnd
        - funlen
        - goconst
        - dupl

    # 排除生成的文件
    - path: ".*\\.pb\\.go"
      linters:
        - lll
        - govet

    # 排除 mock 文件
    - path: ".*_mock\\.go"
      linters:
        - govet
        - errcheck

    # 排除 main 函数的复杂度检查
    - text: "cyclomatic complexity"
      source: "func main\\("

  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - dupl
        - mnd
        - goconst
      severity: warning

    - linters:
        - gosec
        - errcheck
        - govet
      severity: error