[supervisord]
nodaemon=true
logfile=/home/appuser/logs/supervisord.log
pidfile=/home/appuser/supervisord.pid

[program:influxdb]
command=/usr/local/bin/influxd --bolt-path /home/appuser/data/influxdb/influxd.bolt --engine-path /home/appuser/data/influxdb/engine
priority=5
autostart=true
autorestart=true
stdout_logfile=/home/appuser/logs/influxdb.log
stderr_logfile=/home/appuser/logs/influxdb.err

# 初始化influxdb
[program:init_influxdb]
command=/home/appuser/scripts/init_influxdb.sh
priority=10
autostart=true
autorestart=false
startsecs=0
exitcodes=0
stdout_logfile=/home/appuser/logs/init_influxdb.log
stderr_logfile=/home/appuser/logs/init_influxdb.err

[program:redis]
command=sh -c "/usr/bin/redis-server --bind 0.0.0.0 --requirepass \"$WEBSOFT9_REDIS_PASSWORD=\""
priority=20
autostart=true
autorestart=true
stdout_logfile=/home/appuser/logs/redis.log
stderr_logfile=/home/appuser/logs/redis.err

[program:api-service]
command=/home/appuser/api-service
priority=30
autostart=true
autorestart=true
stdout_logfile=/home/appuser/logs/api-service.log
stderr_logfile=/home/appuser/logs/api-service.err
