[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/home/appuser/supervisord.pid
silent=true

[program:api-service]
command=/home/appuser/scripts/start_server.sh
priority=1
autostart=true
autorestart=false
startsecs=0
exitcodes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
