services:
  webox:
    #image: websoft9dev/webox-server:$WEBOX_VERSION
    image: api-service:latest
    container_name: websoft9-webox
    restart: unless-stopped
    env_file: .env
    volumes:
      - webox_data:/home/appuser
      - redis_data:/var/lib/redis
    ports:
      - "8080:8080" # Web Service Port
      #- "9090:9090" # RPC Port
    healthcheck:
      test: ["CMD", "sh", "-c", "/home/appuser/scripts/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  default:
    name: websoft9
    external: true

volumes:
  webox_data:
  redis_data:
